name: Update UI version
on:
  repository_dispatch:
    types: [ui-dependency-update]

permissions:
  contents: write
  actions: read
  packages: read

jobs:
  update-ui-version:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
        with:
          ref: main
          persist-credentials: false

      - name: Setup Node
        uses: actions/setup-node@6044e13b5dc448c55e2357c09f80417699197238 # v6.2.0
        with:
          node-version: 22
          registry-url: 'https://npm.pkg.github.com'
          scope: '@netcracker'

      - name: Update ui vesion
        env:
          UI_VERSION: ${{ github.event.client_payload.version }}
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          npm install @netcracker/qip-ui@"$UI_VERSION"

      - name: Commit Changes
        env:
          UI_VERSION: ${{ github.event.client_payload.version }}
        run: |
          git config --global user.name "qubership-actions[bot]"
          git config --global user.email "qubership-actions[bot]@users.noreply.github.com"

          git add package.json package-lock.json
          git commit -m "chore: bump qip-ui to $UI_VERSION"
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git
          git push
