name: Update UI version
on:
  repository_dispatch:
    types: [ui-dependency-update]

permissions:
  contents: write
  actions: read

jobs:
  update-schemas-version:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
        with:
          ref: main
          persist-credentials: false

      - name: Setup Node
        uses: actions/setup-node@6044e13b5dc448c55e2357c09f80417699197238 # v6.2.0
        with:
          node-version: 22
          cache: npm

      - name: Update schemas
        run: npm pkg set dependencies.@netcracker/qip-ui=${{ github.event.client_payload.version }}

      - name: Commit Changes
        run: |
          git config --global user.name "qubership-actions[bot]"
          git config --global user.email "qubership-actions[bot]@users.noreply.github.com"

          git add package.json
          git commit -m "chore: bump qip-ui to ${{ github.event.client_payload.version }}"
          git push origin main
